SELECT TOP 1000 [BuildSK]
      ,[BuildBK]
      ,[BuildID]
      ,[BuildName]
      ,[BuildType]
      ,[BuildDefinitionName]
      ,[DropLocation]
      ,[BuildStartTime]
      ,[LastUpdatedDateTime]
      ,[TeamProjectCollectionSK]
  FROM [Tfs_Warehouse].[dbo].[DimBuild]