//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vueling.StaticContent.Back.JS.Helpers.Impl.ServiceLibrary.Helpers.back
{
    using System;
    
    
    public class Js : Vueling.StaticContent.Back.JS.Helpers.Impl.ServiceLibrary.BaseFolder
    {
        
        private const string TestingHelpers_js_FileName = "TestingHelpers.js";
        
        public Js(string parentPath) : base(parentPath) 
        {
        }

        protected override string currentFolder { get { return "js"; } }

        public string TestingHelpers_js { get { return GetFullPath(TestingHelpers_js_FileName); } }

    }
}
