//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vueling.StaticContent.Back.JS.Helpers.Impl.ServiceLibrary.Helpers
{
    using System;
    
    
    public class Back : Vueling.StaticContent.Back.JS.Helpers.Impl.ServiceLibrary.BaseFolder
    {
        
        public Back(string parentPath) : base(parentPath) 
        {
                Js = new Vueling.StaticContent.Back.JS.Helpers.Impl.ServiceLibrary.Helpers.back.Js(relativePath);
        }

        protected override string currentFolder { get { return "back"; } }

        public Vueling.StaticContent.Back.JS.Helpers.Impl.ServiceLibrary.Helpers.back.Js Js { get; set; }

    }
}
