//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vueling.StaticContent.Back.JS.Helpers.Impl.ServiceLibrary.Helpers
{
    using System;
    
    
    #region 
[System.Diagnostics.CodeAnalysis.SuppressMessage("CustomRules.Maintenability", "VY1004:GlobalNoUseParamlessConstructor")]
static
    public class StaticJS
    {
        
        private const string currentRelPath = "/";

        static StaticJS()  
        {
                Back = new Vueling.StaticContent.Back.JS.Helpers.Impl.ServiceLibrary.Helpers.Back(currentRelPath);
        }

        public static Vueling.StaticContent.Back.JS.Helpers.Impl.ServiceLibrary.Helpers.Back Back { get; set; }

    }
    #endregion
}
